# Generated by Django 5.0.4 on 2026-06-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal_2fa', '0003_webauthncredential_rp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedloginattempt',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
