"""
Django settings for django_examples project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path
from modal_2fa.settings_helper import modal_2fa_apps_admin
try:
    from .sendgrid import password
except ModuleNotFoundError:
    password = 'SENDGRID PASSWORD'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7mqe9(9$nxj&u88oc$6)7&tvid#1x1d#8txxvbt(d0r106%8w4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    *modal_2fa_apps_admin,
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_datatables',
    'django_modals',
    'crispy_forms',
    'examples',
    'ajax_helpers',
    'django_menus',
    'show_src_code',
    'celery',
    'djcelery_email',
    'django_extensions'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_examples.urls'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_examples.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR.joinpath('db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_L10N = False

USE_TZ = False


STATIC_URL = '/static/'

LOGIN_URL = 'auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

WEBAUTHN_RP_ID = 'localhost'

AUTHENTICATION_CUSTOMISATION = 'examples.customise.ExampleCustomise'
AUTHENTICATION_BACKENDS = ['modal_2fa.auth.CookieBackend']
OTP_TOTP_ISSUER = 'TEST 2FA'

CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False

DATE_FORMAT = 'd/m/Y'
DATE_INPUT_FORMATS = ('%d/%m/%Y', '%Y-%m-%d', '%d-%m-%Y')

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = password
EMAIL_PORT = 587
EMAIL_USE_TLS = True

CELERY_BROKER_URL = 'redis://redis:6379'
CELERY_RESULT_BACKEND = 'redis://redis:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

EMAIL_BACKEND = 'djcelery_email.backends.CeleryEmailBackend'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

DEFENDER_REDIS_URL = 'redis://redis:6379'
DEFENDER_LOGIN_FAILURE_LIMIT = 6
DEFENDER_COOLOFF_TIME = 10
# The demo serves runserver directly with no proxy in front, so X-Forwarded-For
# is untrusted here. Set True only when a trusted reverse proxy sets that header.
BEHIND_REVERSE_PROXY = False

# Behind a reverse proxy, set the number of trusted hops so the real client IP is
# read from X-Forwarded-For (REMOTE_ADDR would otherwise be the proxy container).
#   Traefik only:            AUTHENTICATION_TRUSTED_PROXY_COUNT = 1
#   Cloudflare/LB -> Traefik: AUTHENTICATION_TRUSTED_PROXY_COUNT = 2
# AUTHENTICATION_TRUSTED_PROXY_COUNT = 1


# Read the Microsoft/Entra config from the environment (see .env).
MS_CLIENT_ID = os.environ.get('MS_CLIENT_ID')
MS_TENANT_ID = os.environ.get('MS_TENANT_ID')
MS_CLIENT_SECRET = os.environ.get('MS_CLIENT_SECRET')

# Must EXACTLY match a Web redirect URI registered in the Azure App Registration,
# and point at the library's callback route (auth:ms_redirect).
MS_REDIRECT_URI='http://localhost:8010/auth/microsoft/redirect'
